server:
  port: 8085

spring:
  profiles:
    active: "dev"
---
spring:
  profiles: dev

logging:
  level:
    .: ERROR
    org.springframework: INFO
    es.amm: INFO

---
spring:
  profiles: test

server:
  port: 8085
  servlet:
    context-path: /v1

logging:
  level:
    .: ERROR
    org.springframework: INFO
    es.amm: INFO

---
spring:
  profiles: prod

server:
  port: 8085
  servlet:
    context-path: /v2

logging:
  level:
    .: ERROR
    org.springframework: INFO
    es.amm: INFO

